README.md

**Add**  
-  [reifetch](https://github.com/OkaVatti/reifetch) under the shell category. 
**Description** 
- ":cat2: A light fetch script, based on Neofetch, for Linux, MacOS, and BSD"

Add Reifetch

---

README.md

Added disfetch

---

README.md

Add profetch

---

README.md

the main difference of tuatara from disfetch is that tuatara will be highly customizable, while disfetch won't, because it covers minimalism and simplicity. though, they will share some other principles regarding showing only needed information, being fast and reliable and sharing the same handmade logos with the principle of not-more-or-less-than 8 rows.
zig is a new (only 5 years) tasty system programming language with no hidden control flow, no preprocessor and cool `comptime` keyword. it is targeted to most system, providing another option in system/game/embedded/os development.
`neofetch` with no options:
`neofetch  0.28s user 0.12s system 97% cpu 0.411 total`
`neofetch` with only options that `disfetch` has:
`neofetch --disable resolution theme icons term cpu gpu memory wm_theme …

Add tuatara

---

README.md

It's written in C++, customizable,  looks nice and.... works fast

Add sysfex

---

README.md

Rxfetch is a custom system fetching tool that is made in bash script.

Add rxfetch

---

README.md

(it is suffering currently a re-write)

Added sf (Small fetcher)

---

README.md

Yes, I should change the description.

Uwufetch is actually cross platform (even if its description says it is linux only)

---

README.md

Added a Rust neofetch implementation. Currently close to publishing a crate for it, with a scoop package following shortly after.

Add zeitfetch

---

README.md

Hello, I'm the creator of Bfetch and DIYfetch. I would like to add DIYfetch (the successor of Bfetch) to this awesome list!

Add DIYfetch

---

README.md

ramfetch was reported too much on r/linux and i almost had 1k upvotes. aww mannnnnnn
preview:

add ramfetch

---

README.md

I thought this repo is dead now, since there was no activity so i closed the first one:(

feat: Yarsi from @BinaryBrainiacs

---

README.md

Add procfetch

---

README.md

Added a link to my cutefetch shell script

feat: add link to cutefetch

---

README.md

Add hayabusa

---

README.md

Please see the commit [message](https://github.com/beucismis/awesome-fetch/commit/438468ac730c01092237e6a1d23ce7f7efb8a33a) for more information.

README: Update repository owners username and others

---

README.md

Add xFetch

---

README.md

Add terminal-widgets

---

README.md

[Catnap](https://github.com/iinsertNameHere/catnap) - A playful, simple system-information concatenation tool. `nim`

Add Catnap

---

README.md

Adds [turbofetch](https://github.com/ajTronic/turbofetch).

Add turbofetch

---

README.md

Adds [CrabFetch](https://github.com/LivacoNew/CrabFetch), my own project just for full disclosure.

Add CrabFetch

---

README.md

https://github.com/Gobidev/pfetch-rs

Add pfetch-rs

---

README.md

Fixes https://github.com/beucismis/awesome-fetch/issues/67.

Add brofetch

---

README.md

Fixes https://github.com/beucismis/awesome-fetch/issues/65.

Add unifetch

---

README.md

this pr adds:
- [betterfetch](https://github.com/sctech-tr/betterfetch)
- [zfetch](https://github.com/emilydaemon/zfetch)
- [strlx](https://github.com/stx3plus1/strlx)

add betterfetch, zfetch, strlx

---

README.md

https://github.com/GabubuAvailable/gbfetch

add gbfetch

---

README.md

https://github.com/speedie1337/sfetch
https://github.com/stx3plus1/sxl
https://github.com/sctech-tr/scfetch

add scfetch, sxl, sfetch

---

README.md

https://github.com/isa-programmer/githubfetch
I added my github profile fetch program

Add githubfetch

---

README.md

Adds my project, exfetch: https://codeberg.org/izder456/exfetch.git

Add exfetch

---

README.md

Completing issues
